### ISSUE TITLE
Additive residual connections in feed forward network

### ISSUE THREAD

**Issue by zozoMatt** [ahmedrashed-ml/CARCA#3]
In the diagram published in the paper it implies that there's multiplicative residual connections in the feed forward network. It seems that in the code this is actually an additive connection.
https://github.com/ahmedrashed-ml/CARCA/blob/9b415fd4fa21df2f7c9b9c866aa8162e4dcd326f/CARCA.py#L854
It seems that substituting this additive connection for a multiplicative connection yields poor performance

![image](https://user-images.githubusercontent.com/103390753/189265322-1e98e9b4-2035-4099-a456-4dfd3440645b.png)

**Comment by ahmedrashed-ml** [comment]
Thank you for pointing that out, Indeed we found out that on some datasets, the additive residual is better after the FFN layer, but we always used multiplicative residuals after the multi-head attention layers
