### ISSUE TITLE
About generating the positive items list

### ISSUE THREAD

**Issue by ding1995** [ahmedrashed-ml/CARCA#5]
The paper mentions that "The positive items list is constructed by right shifting the input list ...". However, the profile features contain the items except the last interaction, which means that supervised signals have been seen by the model. I am wondering why this will work well. Could you please explain it?

**Comment by ahmedrashed-ml** [comment]
That's a very good question and, indeed, a tricky one. First, it is always possible to train CARCA using a simple rolling window with one target to completely avoid this case but at the cost of more training time/samples. However, we found out that the optimization problem is not exactly trivial when using such a training protocol, especially **when we have attributes**.
We believe the following factors regularize the model and mitigate the triviality problem (Further theoretical analysis is needed):
1) Carefully tuning the dropout induces some random changes in the item representations; hence they are not completely the same in the input and output.
2) Using attributes allows partial similarity to exist between some attributes of the negative and positive items hence it prevents the model from learning the trivial scenario.
3) Adding an extra item to the list also induce a further smaller regularizing effect.
