### ISSUE TITLE
how to use raw data

### ISSUE THREAD

**Issue by HansolWorld** [ahmedrashed-ml/CARCA#6]
I don't know how to use the raw dataset.
I would like to use the amazone beauty reviews datasets downloaded from https://cseweb.ucsd.edu/~jmcauley/datasets/amazon_v2/.
But PreprocessData is not available.
The raw datasets just contain ['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText', 'overall', 'summary', 'unixReviewTime', 'reviewTime'].
No information was found for ["user", "item", "rate", "st"].
How to use raw dataset?

**Comment by ahmedrashed-ml** [comment]
Hi,

You need to connect the review data with the metadata or the image data. You can do this using the item identifier field
