### ISSUE TITLE
how to make Beauty_feat_cat.dat?

### ISSUE THREAD

**Issue by HansolWorld** [ahmedrashed-ml/CARCA#7]

**Comment by HansolWorld** [comment]
i want make Beauty_feat_cat.dat
but i dont get this in Preprocessing.
please method

**Comment by ahmedrashed-ml** [comment]
Hi, 

The Beauty_feat_cat.dat is just a numpy array with size N x F, N: Number of items, F: Number of features. How you generate Beauty_feat_cat is up to you depending on which features you want to use. If you wish to reproduce our results, please use our preprocessed one.

**Comment by dcy0577** [comment]
Hi, how did you generate Men_imgs.dat? Can you provide some code about feature extraction?
