### ISSUE TITLE
How to use User features(such as age, demographics)  to construct the Sequential Recommendation System ?

### ISSUE THREAD

**Issue by np-n** [ahmedrashed-ml/CARCA#8]
I want to train a next-procedure prediction for the medical dataset. After checking the data processing pipeline, what I have figured out is: the emphasis is done on the sequence of item interaction for users along with the timestamp in the loaded data. But there is no consideration of user features.
But, what I know is user features and item features also play a role, In my case, user features are very critical. How I can use such features to design the sequential recommendation system? Thank you!

**Comment by ahmedrashed-ml** [comment]
I would say there can be more than one way of doing that, but I am not sure which one would be the best. The easiest way of doing it is to simply concatenate the user features to the item feature in the sequence.

**Comment by np-n** [comment]
@ahmedrashed-ml, During model initialization, User features are passed as an argument with Item features but empty. See line 1316 in `CARCA.py`.
```
UserFeatures = []
model = Model(usernum, itemnum, args, ItemFeatures, UserFeatures, args.cxt_size,use_res = args.use_res)
```
And you know that item features are passed in order i.e. from 1 to `item_num`. So, in my opinion, it is not possible to concatenate item features with user features. Probably we can pass it separately.

**Comment by ahmedrashed-ml** [comment]
True, but you can simply repeat the user features for each item in the list. Not an efficient way of doing that, but it should work in theory.
