### ISSUE TITLE
How to load and perform next-item prediction on new data?

### ISSUE THREAD

**Issue by np-n** [ahmedrashed-ml/CARCA#9]
To perform inference on new Data, and predict the next-item sequence, there is no pipeline/code available. So, could you please suggest me pipeline of inference?

**Comment by ahmedrashed-ml** [comment]
Unfortunately, this will need some modification and upgrades to the current code base. I would first save all model artifacts (mode, data scaler, etc.) somewhere and load them during the inference. On the other hand, in the inference phase, I would 
1) Preprocess the inference data the same as the training data with the already saved model artifacts. 
2) Load the model into the GPU memory
3) Save the features of the inference data + the user history data on the GPU. (This can be done per user request or depending on how much data you have during inference. You can also cache the scores if the users history doesn't change much and you have huge large of items to score)
4) Predict the next item score by using an input sequence of the users' latest historical interactions and use a target sequence containing the features of all items you want to score.

**Comment by np-n** [comment]
@ahmedrashed-ml, Thanks for your response, could you please add that pipeline? So, that it becomes more easier for me to understand and modify accordingly.

**Comment by ahmedrashed-ml** [comment]
That would be very difficult for me to do currently as it will require some extensive modification and effort to do. Also I currently don't have enough spare time to do that. Really sorry :(
